version: '3.9'

services:
  playlists-synchronizer-app:
    container_name: playlists-synchronizer-api
    build: ./
    command: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=0961533469Vi
  db:
    restart: always
    image: postgres:latest
    env_file: ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=playlists_synchronizer
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.15.2
    profiles: [ "tools" ]
    volumes:
      - ./Backend/schema:/schema
    entrypoint:
      [
        "migrate",
        "-path",
        "/schema",
        "-database",
        "postgres://postgres:$DB_PASSWORD@db:5432/playlists_synchronizer?sslmode=disable",
      ]
    command: [ "up" ]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db: {}